name: clean_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.6
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - anyio=4.2.0
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - click=8.1.7
  - dnspython=2.6.1
  - exceptiongroup=1.2.0
  - fastapi=0.112.2
  - frozenlist=1.4.1
  - h11=0.14.0
  - idna=3.7
  - iniconfig=1.1.1
  - joblib=1.4.2
 # - libcxx
  - libffi=3.4.4
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libsqlite=3.45.2
  - libxgboost=2.1.1
  - llvm-openmp=14.0.6
  - multidict=6.1.0
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - passlibX
  - pip=24.2
  - py-xgboost=2.1.1
  - pybind11-abi=4
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pyjwt=2.9.0
  - pymongo=4.9.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-dotenv=1.0.1
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - setuptools=75.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.45.2
  - starlette=0.38.2
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - uvicorn=0.20.0
  - wheel=0.44.0
  - xgboost=2.1.1
  - xz=5.4.6
  - yarl=1.12.1
  - zlib=1.3.1
  - pip:
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - cryptography==43.0.1
      - docker==7.1.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - pluggy==1.5.0
      - pycparser==2.22
      - pyopenssl==24.2.1
      - pytest==8.3.3
      - pytest-asyncio==0.24.0
      - requests==2.32.3
      - urllib3==2.2.3