services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lfb_api
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      PYTHONPATH: ${PYTHONPATH}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - lfb_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: R0vTrwRkhguP0tK4
    ports:
      - "27017:27017"
    networks:
      - lfb_network
    command: ["mongod", "--auth", "--bind_ip_all", "--port", "27017"]

  mongo-express:
    image: mongo-express:latest
    container_name: lfb_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: R0vTrwRkhguP0tK4
      ME_CONFIG_MONGODB_URL: mongodb://admin:R0vTrwRkhguP0tK4@mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - api
      - mongodb
    networks:
      - lfb_network

networks:
  lfb_network:
    driver: bridge