services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lfb_api
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      PYTHONPATH: ${PYTHONPATH}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - lfb_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ยง{MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ยง{MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - lfb_network
    command: ["mongod", "--auth", "--bind_ip_all", "--port", "27017"]

networks:
  lfb_network:
    driver: bridge