FROM apache/airflow:2.10.2

USER root

RUN apt-get update && sudo apt-get install gnupg curl

USER airflow

RUN pip install --no-cache-dir joblib pandas numpy scikit-learn xgboost python-dotenv pymongo apache-airflow-providers-mongo
