name: CD Pipeline #Trigger Airflow DAG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Täglich um Mitternacht (kann angepasst werden)
  push:
    branches:
      - main

jobs:
  trigger_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Install Docker and Docker Compose
    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker docker-compose

    # Set up and start the Docker Compose services
    - name: Set up Docker Compose
      run: |
        docker-compose up --build --force-recreate -d

    - name: Wait for Airflow to be ready
      run: |
        until $(curl --output /dev/null --silent --head --fail http://localhost:8080); do
          echo "Waiting for Airflow webserver..."
          sleep 20
        done

    # Install Python dependencies (BeautifulSoup and requests)
    - name: Install BeautifulSoup
      run: |
        pip install beautifulsoup4 requests

    - name: Trigger Airflow DAG using Python Client
      run: |
        python ./airflow/trigger_dag.py

    # Commit and push changes in ./model-folder
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add ./model/*
        git commit -m "Updated model and versioned old model"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Tear down the Docker Compose services
    - name: Tear down Docker Compose
      run: docker-compose down